### ISSUE TITLE
Character sheets can't be retrieved on dual-stack or IPv6-only hosts

### ISSUE THREAD

**Issue by hobarrera** [gtkevemon/gtkevemon#15]
At home, I've an IPv6-only network, which uses NAT64 for accesing remote IPv4-only hosts. Here's very a very brief summary of how this works:
 * My ISP's DNS will map A records for hosts with no AAAA record to something in a specially reserved zone, eg: 192.30.252.128 -> 64:ff9b::192.30.252.128. (That's DNS64)
 * On of the outbound routers/gatways, then translates any IP on the 64:ff9b::/96 range to IPv4. (That's NAT64).

By simply using the AAAA DNS record when establishing an HTTP connection, gtkevemon should work on this sort of enviroment.

-----

On the other hand, I've access to other, dual-stack networks elsewhere. gtkevemon did not work there either. This network has NAT64 *and* old-school NAT (eg: hosts have IPv4 addresses and routes). I can't entirely unsure why gtkeveon did not work there. :(

**Comment by hobarrera** [comment]
I *big* apology. It turns out my API Key had just expired (very recently), so the 403 was due to that. I noticed this when I roamed to an IPv4 network and it failed to update too (I'm a bit away from eve lately).

So, yeah, this patch works perfectly, sorry for this mis-testing before!

Just for the log: I tested this on an IPv6-only host, which no IPv4 connectivity and after deleting .gtkevemon (because I wanted to make sure *nothing* was being cached).

Thanks!

**Comment by hobarrera** [comment]
Oh, btw, please open a PR for this: it would close #18 (I'm not sure why I clicked close since this isn't merged yet, but we still have #18 open anyway).

Again, thanks!

**Comment by henrikolsson** [comment]
That explains it! Cool, the code is quite messy now, i need to clean it up a bit before i send a PR.

**Comment by simonfuhrmann** [comment]
This is good news. Are the changes generic enough that it will continue to work on a single-stack-IPv4 host? I have to admit I am not familiar with IPv6 and cannot properly review the code. Please make sure it's well tested on different IP configurations.

**Comment by henrikolsson** [comment]
Yes it works fine on ipv4 as well. One potential issue is compiling it on different platforms, i only have access to linux machines..

**Comment by hobarrera** [comment]
Any news on that PR? 😄

**Comment by henrikolsson** [comment]
I just looked at it a bit, could you verify that the branch ipv6_cleaned_up still works for you with ipv6?

**Comment by hobarrera** [comment]
Nope:

```
$ gtkevemon 
Initializing SSL subsystem...
Error: The download for SkillTree.xml failed: Connection refused
Error: The download for CertificateTree.xml failed: Connection refused
```

**Comment by henrikolsson** [comment]
That is really strange, it works for me when i force it to connect to an ipv6 host.. Are you 100% sure there is no other issue with your network?

**Comment by hobarrera** [comment]
Sorry, I just realized why I'm mistesting so much: I've /usr/bin/gtkevemon, and /usr/local/bin/gtkevemon, so I kept on screwing up. I've gotten rid of both and will no properly (and cleanly) test the newer branch.

**Comment by hobarrera** [comment]
Ok, properly tested now: I can confirm that it gtkevemon works fine over IPv6 with the new `ipv6_cleaned_up` branch.

**Comment by simonfuhrmann** [comment]
I will wait for pull request for this one. 

Can the both if you also take a look at and test this PR and give your opinion? 

#27 Get rid of the notion of "training_spph".

Thanks.
