### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by hobarrera** [gtkevemon/gtkevemon#32]
There are no release tags (eg: 1.8.2, etc) on the repo on github.

Could you upload these (and, possibly, create a new release too)? These are very useful for downstream (eg: distro packages), and in some cases, necesary to follow upstream (eg: your) versioning, etc.

**Comment by simonfuhrmann** [comment]
Removed the old SVN version checker, released v1.10.

**Comment by hobarrera** [comment]
Thanks a bunch! :smile:
