### ISSUE TITLE
Fedora 21 Install Error

### ISSUE THREAD

**Issue by diegobh** [gtkevemon/gtkevemon#36]
Ive installed:

- gcc-c++
- libxml2-devel
- gtkglextmm-devel

And i can install ok.

But i got errors:

The download for SkillTree.xml failed.
SSL error connecting.

and

The download for CertificateTree.xml failed.
SSL error connecting.

So i went to the options and disabled use ssl. But i got new errors:

The download for SkillTree.xml failed.
Received HTTP code 301: Moved Permanently

and

The download for CertificateTree.xml failed.
Received HTTP code 301: Moved Permanently

...

How to fix it, please?

I'm using Fedora 21 64bits.

Thank you!!!

**Comment by simonfuhrmann** [comment]
This issue has just been fixed in the latest version. Please update your version.
