### ISSUE TITLE
Error requesting SkillQueue.xml! Using Cache.

### ISSUE THREAD

**Issue by nizmogtr** [gtkevemon/gtkevemon#38]
Initializing SSL subsystem...
Request XML: CharacterSheet.xml ...
Request XML: SkillQueue.xml ...
Parsing XML: SkillTree.xml... 453 skills.
Server info: Tranquility online. Players: 18388
SSL error connecting!
4421529680:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:347:
Warning: SSL error connecting.
Warning: Using CharacterSheet.xml from cache!
Parsing XML: CharacterSheet.xml ...
Parsing XML: CertificateTree.xml... 0 certs.
Error: Failed to request CharacterSheet.xml: SSL error connecting.
SSL error connecting!
4422066256:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:347:
Warning: SSL error connecting.
Warning: Using SkillQueue.xml from cache!
Parsing XML: SkillQueue.xml ...
Error: Failed to request SkillQueue.xml: SSL error connecting.
Server info: Serenity offline. Connection timed out
Server info: Singularity online. Players: 44

----------------------------------------------------------------------------------------------------------------------------------------
Request XML: CharacterSheet.xml ...
Request XML: SkillQueue.xml ...
Warning: Received HTTP code 301: Moved Permanently
Warning: Using SkillQueue.xml from cache!
Parsing XML: SkillQueue.xml ...
Error: Failed to request SkillQueue.xml: Received HTTP code 301: Moved Permanently
Warning: Received HTTP code 301: Moved Permanently
Warning: Using CharacterSheet.xml from cache!
Parsing XML: CharacterSheet.xml ...
Error: Failed to request CharacterSheet.xml: Received HTTP code 301: Moved Permanently

**Comment by simonfuhrmann** [comment]
This issue has just been fixed in the latest version. Please update your version.
