### ISSUE TITLE
SSL errors when fetching skillqueue

### ISSUE THREAD

**Issue by ecraven** [gtkevemon/gtkevemon#41]
Since yesterday (2015-05-27), I get SSL certificate verification errors when using gtkevemon. Maybe a certificate changed?

**Comment by simonfuhrmann** [comment]
Indeed. `140297015907904:error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed:s3_clnt.c:1180`

**Comment by ecraven** [comment]
It seems api.eveonline.com now uses three certificates (all different than the ones in certificates.h), however just adding them in the obvious way didn't work here for me. Also, the code seems to use SSLv23, TLSv1_2 might be better?
I haven't had much time to play around with this, but my tests so far have been unsuccessful :(

**Comment by lord-carlos** [comment]
Same here.
Give me a shout if you need any testers or however I can help.

**Comment by Winter-Knight** [comment]
I created a [temporary workaround for this issue](https://github.com/Winter-Knight/gtkevemon/commit/3332f7a064be0d76a410510f7f0c694fe17c24ef). It bypasses most of the networking code and replaces it with wget. It forces ssl and ignores user settings such as proxy and http method. It does not check for errors.

This patch requires wget is installed in your system. If you're using Linux, you probably already have it, or you can download it through your package manager. If you're using Windows, you can download [binaries here](http://gnuwin32.sourceforge.net/packages/wget.htm) and make sure it is installed in your path.

I wrote this patch intending it as a temporary workaround until a proper fix is implemented.

**Comment by waveclaw** [comment]
I think the workaround brings up an important design question: should gtkevemon be handling the HTTP and SSL connection directly?

libcurl exists (http://curl.haxx.se/libcurl/c/simplessl.html or http://curl.haxx.se/libcurl/c/curlgtk.html) and is required for building other Gtk-based tools like transmission-gtk.  

But libcurl is effectively the same as this workaround.  It does not depend on what the wget binary is in your path.  It also is does push SSL management into the platform where HOWO-TO documentation exists for certificate and certificate authority management.

**Comment by Winter-Knight** [comment]
I completely agree. Maintaining one's own network and http code is a lot of work, and isn't really necessary. And a bit prone to failure, as you're likely to come upon edge cases that programs like wget and curl have already ironed out. I was actually looking at the libcurl code samples and functions yesterday. If you guys want, I could create a fork, rip out most of the http and networking code from gtkevemon and replace it with libcurl.

**Comment by ecraven** [comment]
I agree as well, Simon, would you be willing to merge such a branch? Winter-Knight, depending on how much time you have, I can participate in the work needed to get this done.

**Comment by simonfuhrmann** [comment]
I am not a huge fan of dependencies, but I guess you have a point there. Using curl would remove quite a bit of code, which is always welcome. So if one of you finds the time to do that, it would be great. Thanks.

**Comment by Winter-Knight** [comment]
OK. I'll get to it.

ecraven, how about if I introduce libcurl to the code, and then when I'm done you implement code to check that the certificates are valid and as expected?

**Comment by ecraven** [comment]
sounds perfect :)

**Comment by Winter-Knight** [comment]
I think it's ready. Take a look.

**Comment by ecraven** [comment]
looks good to me, I tested it, works very well.
https://github.com/simonfuhrmann, could you merge this? then I'll implement the SSL certificate verification on top of it, and also rebase my implant fixes (to pull from a file hosted on github, if that is ok?)

**Comment by simonfuhrmann** [comment]
I will take a look in a sec. But please don't mix this up with the implants PR. First things first. Once the networking stuff is working again, we can take a look at the implants issue, separately.

**Comment by ecraven** [comment]
yes, that was my intention, first this, then i'll fix the SSL certificate verification, then we can talk about the implants (as it will finally be possible to download files from github or any other location you wish).

**Comment by simonfuhrmann** [comment]
We're almost there.

**Comment by simonfuhrmann** [comment]
Curl code is pulled.

**Comment by lord-carlos** [comment]
What package do I need in debian to compile it? Or is it not enduser ready?

**Comment by ecraven** [comment]
perfect, thank you, built on arch linux, works fine!

**Comment by ecraven** [comment]
Closing this, as it is resolved.
