### ISSUE TITLE
Options for Packaging with RPM

### ISSUE THREAD

**Issue by waveclaw** [gtkevemon/gtkevemon#43]
The Thanks
==========
Thank you for providing this amazing tool.  It has saved me considerable gnashing of teeth over skill plans.

The Package
==========
As a token of my gratitude I have written a basic **Unofficial** cross-distribution package for GtkEveMon on the SuSE Open Build Service.  This uses the libcurl version.

https://build.opensuse.org/package/show/home:waveclaw:gtkevemon/gtkevemon

This package *should* install on Fedora or openSUSE type Linux distributions that have libcurl, libxml++ and gtkmm of some type.  I use the package locally on openSUSE with my accounts.

The Issues
=========
These issues bellow need not be resolved as they are packaging-related only.

Two patches I have to provide in the package change the following:
 1. Update the desktop file to use approved Categories on openSUSE (see https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories)
 2. Change the Makefiles to support DESTDIR since RPM build tools like to use a %buildroot
 3. Update the install path to /usr/bin since /usr/local/bin would trigger an error on the very thorough Open Build 

The Future
=========
Normally I build a relocatable package.  This is so that the package could use /usr/local, /opt, /whatever/you/feel/like at install time.  The elegant simplicity of the existing build process used by the GtkEveMon team dissuades me from retrofitting a complex system to do this.

If the team chooses to support DESTDIR and %prefix I would be happy to rebuild the package to support relocation.

**Comment by simonfuhrmann** [comment]
This is great. Thank you.

I can change the build system to use DESTDIR and BINDIR which can then be defined from outside the Makefile. But it will take two weeks or so. Thanks for the patience.

**Comment by dallenwilson** [comment]
DESTDIR would be useful for the Ubuntu/Mint/Debian packages at Launchpad, as well. Currently we patch the makefile prior to packaging, instead.

**Comment by simonfuhrmann** [comment]
Anyone, feel free to send me a PR with DESTDIR and BINDIR so that it defaults to the current settings. Otherwise it will have to wait a while. :)

**Comment by dallenwilson** [comment]
PR created!

**Comment by simonfuhrmann** [comment]
PR merged. Please check if this works for packaging. Thanks everybody.
