### ISSUE TITLE
Port to GTK3

### ISSUE THREAD

**Issue by skybon** [gtkevemon/gtkevemon#46]
Should be as straightforward as updating method names.

**Comment by simonfuhrmann** [comment]
I guess once we ported to GTK3, it won't work with GTK2 anymore. Is GTK3 considered to be available on the majority of systems by now?

**Comment by skybon** [comment]
All, unless we include ancient and unsupported installations.

**Comment by dallenwilson** [comment]
A quick check of launchpad.net shows gtk3 support was included as far back
as 2012.04, for what that's worth. I don't know about Debian.

**Comment by simonfuhrmann** [comment]
I would accept a PR with this port. However, it might not be as easy as just renaming a couple of calls.
