### ISSUE TITLE
Tranquility and Singularity server status showing offline, when they are online as of Mar 28, 2016 

### ISSUE THREAD

**Issue by nizmogtr** [gtkevemon/gtkevemon#57]
Tranquility and Singularity server status showing offline, when they are online as of Mar 28, 2016

**Comment by simonfuhrmann** [comment]
Maybe the IP addresses of the servers changed. Does anyone know the new IPs?

**Comment by simonfuhrmann** [comment]
To update to the new IP addresses, the old ones have to be deleted from the configuration file.

**Comment by mkaito** [comment]
Does not seem to work for me.
