### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by nematoad** [gtkevemon/gtkevemon#64]
Guys I tried to make gtkevemon.  All was well until the end when I was left with the following errors:

gui/guicharexport.cc: In constructor ‘GuiCharExport::GuiCharExport(ApiCharSheetPtr)’:
gui/guicharexport.cc:51:14: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   close_but->set_image_from_icon_name("widnow-close", Gtk::ICON_SIZE_BUTTON);
              ^
Makefile:106: recipe for target 'gui/guicharexport.o' failed
make[2]: *** [gui/guicharexport.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gui/gtktrainingplan.cc: In constructor ‘GtkTrainingPlan::GtkTrainingPlan()’:
gui/gtktrainingplan.cc:590:25: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->delete_plan_but.set_image_from_icon_name("edit-delete", Gtk::ICON_SIZE_MENU);
                         ^
gui/gtktrainingplan.cc:591:25: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->create_plan_but.set_image_from_icon_name("document-new", Gtk::ICON_SIZE_MENU);
                         ^
gui/gtktrainingplan.cc:592:25: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->rename_plan_but.set_image_from_icon_name("gtk-edit", Gtk::ICON_SIZE_MENU);
                         ^
gui/gtktrainingplan.cc:593:25: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->export_plan_but.set_image_from_icon_name("document-save-as", Gtk::ICON_SIZE_MENU);
                         ^
gui/gtktrainingplan.cc:594:25: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->import_plan_but.set_image_from_icon_name("document-revert", Gtk::ICON_SIZE_MENU);
                         ^
gui/gtktrainingplan.cc:601:24: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->clean_plan_but.set_image_from_icon_name("edit-clear", Gtk::ICON_SIZE_MENU);
                        ^
gui/gtktrainingplan.cc:605:24: error: ‘class Gtk::Button’ has no member named ‘set_image_from_icon_name’
   this->clean_plan_but.set_image_from_icon_name("network-workgroup", Gtk::ICON_SIZE_MENU);
                        ^
Makefile:106: recipe for target 'gui/gtktrainingplan.o' failed
make[2]: *** [gui/gtktrainingplan.o] Error 1
make[2]: Leaving directory '/home/andrew1/eve/gtk_evemon/gtkevemon-master/src'
Makefile:93: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/andrew1/eve/gtk_evemon/gtkevemon-master/src'
Makefile:5: recipe for target 'all' failed
make: *** [all] Error 2

Thank you

**Comment by simonfuhrmann** [comment]
The function exists until Since gtkmm 3.10. What version are you using? Ask your package manager.

**Comment by nematoad** [comment]
gtkmm3.0_1

Looks like PCLinuxOS's rolling release is a little behind on this one.

I'll try and see if I can get a reply from Texstar or one of the maintainers to see if they can update the version on the repo. I'll get get back to you if I have any luck

**Comment by nematoad** [comment]
Right, I've been in contact with the people at PCLinuxOS. 

I was wrong in thinking that the gtkmm was an old one it is in fact at version 3.4.2.

Have you any ideas on what I am getting wrong here?

Thanks.

**Comment by simonfuhrmann** [comment]
Because 3.4 < 3.10?

**Comment by nematoad** [comment]
Ah, right.  Sorry my eye-sight is not as good as it was and I misread your post.  I'll take it up with PCLOS and see what they say.

**Comment by simonfuhrmann** [comment]
Maybe you can make a point by mentioning that 3.4 is about 4 years old.
https://mail.gnome.org/archives/gtkmm-list/2012-April/msg00023.html
Closing this.
