### ISSUE TITLE
UI fails outside of integrated WM environments (ie, "standard X")

### ISSUE THREAD

**Issue by ExecutorElassus** [gtkevemon/gtkevemon#66]
I run FVWM, and the UI is failing to draw button edges, space text properly, etc. This is a general problem with, say, gtk-3 apps running outside of GNOME/Ubuntu's integrated WM environments: while they work fine in those WMs, they fail terribly outside of them. 

Would there be a way to build GtkEveMon for other WMs, say by relying on gtk-2, or using Qt?

Cheers

**Comment by simonfuhrmann** [comment]
I suppose it's not an issue with your WM, but with your GTK3 theme. Try changing that. Unfortunately, there is no GTK2 or Qt support.
