### ISSUE TITLE
Crash on opening configuration window

### ISSUE THREAD

**Issue by lxnt** [gtkevemon/gtkevemon#7]
(gtkevemon:3802): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: Path to key does not exist: versionchecker.enabled

Trace/breakpoint trap (core dumped)

Workaround: add the following lines to ~/.gtkevemon/gtkevemon.conf

[versionchecker]
  enabled = false

PS. 
That was the most uninformative gdb backtrace I've ever seen. 
C++ exceptions - ewww. Most useless, wrong and messed up feature of the language, why would you think of using them?

**Comment by simonfuhrmann** [comment]
Yea, the issue with the backtrace is that this is a Gtk issued exception, so it's basically impossible to use backtraces like this with Gtk. This issue has been fixed in commit 274fa9ee20d6ec84b3f528568df9e5f66664b582.
